### ISSUE TITLE
 HTTP 404 for profiles that don't exist

### ISSUE THREAD

**Issue by larrysalibra** [openname/resolver#28]
Error handling for many consumer libraries would much easier if the resolver responded with HTTP status code 404 for profiles that don't exist (or are reserved).  Currently the resolver responds with 200 when a profile doesn't exist.

Happy to submit a pull request.

**Comment by muneeb-ali** [comment]
Thanks for pointing it out! Pull request would be great.

**Comment by shea256** [comment]
Wasn't there a longer conversation on this? I wanted to reference it and I can't find it anywhere.

**Comment by muneeb-ali** [comment]
It's here: https://github.com/namesystem/resolver/pull/37

**Comment by shea256** [comment]
Yeah actually just found it, thank you.
